services:
  test-automation:
    container_name: cypress-automation
    build:
      context: .
      dockerfile: Dockerfile
    # shell run not working on 'Play with Docker' but fine with 'Docker Desktop'
    # entrypoint: /bin/bash -c "cypress/support/docker.sh"
    entrypoint: cypress run